### ISSUE TITLE
"TypeError: Cannot read property 'toString' of undefined" on docker run

### ISSUE THREAD

**Issue by wojkel** [danielwestendorf/breezy-pdf-lite#102]
I wanted to run server on my local machine using docker as described in README.md but it fails.
When I use tag `v0.0.4` it builds fine though.
```
$ sudo docker run -it -p 5002:5002 -e "DEBUG=breezy-pdf-lite:*" -e "PORT=5002" -e "PRIVATE_TOKEN=YOURSUPERSECRETTOKEN" danielwestendorf/breezy-pdf-lite:latest 
Starting Google Chrome
(node:6) ExperimentalWarning: The fs.promises API is experimental
TypeError: Cannot read property 'toString' of undefined
    at Launcher.<anonymous> (/usr/src/app/node_modules/chrome-launcher/dist/chrome-launcher.js:189:64)
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/chrome-launcher/dist/chrome-launcher.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/node_modules/chrome-launcher/dist/chrome-launcher.js:8:12)
    at spawnPromise (/usr/src/app/node_modules/chrome-launcher/dist/chrome-launcher.js:174:41)
    at Launcher.<anonymous> (/usr/src/app/node_modules/chrome-launcher/dist/chrome-launcher.js:192:16)
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/chrome-launcher/dist/chrome-launcher.js:12:71
    at new Promise (<anonymous>)
Exiting

```

**Comment by danielwestendorf** [comment]
It looks like the latest version of chrome launcher breaks compatibility with node v10. Thanks for reporting, I'll get this fixed and cut a new version.

**Comment by danielwestendorf** [comment]
Pull the latest image and give it another shot! `docker pull danielwestendorf/breezy-pdf-lite:latest`

**Comment by wojkel** [comment]
It works, thanks!
